import { Book } from './types';

export const initialBooks: Book[] = [
  {
    id: '1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    cover: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=400',
    category: 'Fiction',
    subcategory: 'Contemporary Fiction',
    isbn: '9780525559474',
    publishedYear: 2020,
    publisher: 'Viking',
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
    pages: 304,
    language: 'English',
    rating: 4.5,
    status: 'available',
    location: 'Shelf A3',
    tags: ['philosophical', 'fantasy', 'life choices'],
    borrowHistory: []
  },
  {
    id: '2',
    title: 'Atomic Habits',
    author: 'James Clear',
    cover: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400',
    category: 'Self-Help',
    subcategory: 'Personal Development',
    isbn: '9780735211292',
    publishedYear: 2018,
    publisher: 'Penguin Random House',
    description: 'An easy and proven way to build good habits and break bad ones.',
    pages: 320,
    language: 'English',
    rating: 4.8,
    status: 'borrowed',
    location: 'Shelf B2',
    tags: ['habits', 'productivity', 'psychology'],
    borrowHistory: [
      {
        borrowDate: new Date('2024-03-01'),
        returnDate: null,
        borrower: 'John Smith',
        condition: 'good',
        notes: 'Borrowed for book club discussion'
      }
    ]
  },
  {
    id: '3',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    cover: 'https://images.unsplash.com/photo-1614544048536-0d28caf77f41?auto=format&fit=crop&q=80&w=400',
    category: 'Science Fiction',
    subcategory: 'Space Opera',
    isbn: '9780593135204',
    publishedYear: 2021,
    publisher: 'Ballantine Books',
    description: 'A lone astronaut must save the earth from disaster in this incredible new science-based thriller.',
    pages: 496,
    language: 'English',
    rating: 4.9,
    status: 'available',
    location: 'Shelf C1',
    tags: ['space', 'adventure', 'science'],
    borrowHistory: []
  },
  {
    id: '4',
    title: 'Dune',
    author: 'Frank Herbert',
    cover: 'https://images.unsplash.com/photo-1506466010722-395aa2bef877?auto=format&fit=crop&q=80&w=400',
    category: 'Science Fiction',
    subcategory: 'Classic Sci-Fi',
    isbn: '9780441172719',
    publishedYear: 1965,
    publisher: 'Ace Books',
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.',
    pages: 412,
    language: 'English',
    rating: 4.7,
    status: 'available',
    location: 'Shelf C2',
    tags: ['classic', 'desert', 'politics'],
    borrowHistory: []
  },
  {
    id: '5',
    title: 'The Design of Everyday Things',
    author: 'Don Norman',
    cover: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&q=80&w=400',
    category: 'Technology',
    subcategory: 'Design',
    isbn: '9780465050659',
    publishedYear: 2013,
    publisher: 'Basic Books',
    description: 'A powerful primer on how—and why—some products satisfy customers while others only frustrate them.',
    pages: 368,
    language: 'English',
    rating: 4.6,
    status: 'available',
    location: 'Shelf D1',
    tags: ['design', 'psychology', 'technology'],
    borrowHistory: []
  },
  {
    id: '6',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    cover: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400',
    category: 'Fiction',
    subcategory: 'Philosophical Fiction',
    isbn: '9780062315007',
    publishedYear: 1988,
    publisher: 'HarperOne',
    description: 'A mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.',
    pages: 208,
    language: 'English',
    rating: 4.7,
    status: 'borrowed',
    location: 'Shelf A1',
    tags: ['philosophy', 'journey', 'spiritual'],
    borrowHistory: [
      {
        borrowDate: new Date('2024-02-15'),
        returnDate: null,
        borrower: 'Sarah Johnson',
        condition: 'excellent',
        notes: 'Book club selection for March'
      }
    ]
  },
  {
    id: '7',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    cover: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=400',
    category: 'Technology',
    subcategory: 'Programming',
    isbn: '9780132350884',
    publishedYear: 2008,
    publisher: 'Prentice Hall',
    description: 'A handbook of agile software craftsmanship that helps programmers write better code.',
    pages: 464,
    language: 'English',
    rating: 4.8,
    status: 'available',
    location: 'Shelf D2',
    tags: ['programming', 'software', 'best practices'],
    borrowHistory: []
  },
  {
    id: '8',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    cover: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&q=80&w=400',
    category: 'Finance',
    subcategory: 'Personal Finance',
    isbn: '9780857197689',
    publishedYear: 2020,
    publisher: 'Harriman House',
    description: 'Timeless lessons on wealth, greed, and happiness. Doing well with money is not necessarily about what you know.',
    pages: 256,
    language: 'English',
    rating: 4.7,
    status: 'available',
    location: 'Shelf E1',
    tags: ['finance', 'psychology', 'wealth'],
    borrowHistory: []
  },
  {
    id: '9',
    title: 'The Art of War',
    author: 'Sun Tzu',
    cover: 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&q=80&w=400',
    category: 'Philosophy',
    subcategory: 'Military Strategy',
    isbn: '9781590302255',
    publishedYear: 2000,
    publisher: 'Shambhala',
    description: 'An ancient Chinese military treatise dating from the 5th century BC.',
    pages: 273,
    language: 'English',
    rating: 4.5,
    status: 'available',
    location: 'Shelf F1',
    tags: ['strategy', 'leadership', 'classic'],
    borrowHistory: []
  },
  {
    id: '10',
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    cover: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=400',
    category: 'Fiction',
    subcategory: 'Psychological Thriller',
    isbn: '9781250301697',
    publishedYear: 2019,
    publisher: 'Celadon Books',
    description: 'A woman shoots her husband five times and then never speaks another word.',
    pages: 336,
    language: 'English',
    rating: 4.6,
    status: 'borrowed',
    location: 'Shelf A4',
    tags: ['thriller', 'mystery', 'psychological'],
    borrowHistory: [
      {
        borrowDate: new Date('2024-02-28'),
        returnDate: null,
        borrower: 'Michael Chen',
        condition: 'good',
        notes: 'Highly recommended by book club'
      }
    ]
  }
];